/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Country implements org.apache.thrift.TEnum {
  AMERICA(0),
  JAPAN(1),
  CANADA(2);

  private final int value;

  private Country(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Country findByValue(int value) { 
    switch (value) {
      case 0:
        return AMERICA;
      case 1:
        return JAPAN;
      case 2:
        return CANADA;
      default:
        return null;
    }
  }
}
